### ISSUE TITLE
Error when setting viewport in .pa11yci config file 

### ISSUE THREAD

**Issue by cvolpe-ecobee** [pa11y/pa11y-ci#107]
I followed the documentation for setting a viewport in the config file, but when I do so I get the following error when pa11y tries to run:

`Error: page.setRequestInterception is not a function`

**Expectation**
When setting a viewport in the pa11y config file, the test execution runs as expected against the given viewport. 

**Actual**
I get the following error when setting a viewport in the config file:

`Error: page.setRequestInterception is not a function`

**Additional info**

Config file:

```
{
	standard: 'WCAG2AA',
	defaults: {
		headers: {
			Authorization: `Basic ${auth}`,
		},
		wait: '1000',
		page: {
                    viewport: {
                        width: 320,
                        height: 480,
			isMobile: true
            },
		},
		concurrency: 5,
		runners: ['axe'],
	},
	urls: [
            "http://www.example.com",
	],
}
```

**Comment by 42tte** [comment]
Have a look at PR https://github.com/pa11y/pa11y-ci/pull/104

**Comment by cvolpe-ecobee** [comment]
Thanks @42tte!

**Comment by josebolos** [comment]
Hopefully this is fixed now, please reopen the issue if not.
