### ISSUE TITLE
How to validate the after login pages by using pa11y-ci

### ISSUE THREAD

**Issue by devandqatools** [pa11y/pa11y-ci#112]
i need to validate the pages after login, how to do?

**Comment by kkoskelin** [comment]
You may very well need to script this using `actions` unless you have a way to supply a token in a query-string that automatically takes you to the desired page.
Here are some examples of `actions`: https://github.com/pa11y/pa11y#actions
Here's a repository on which I'm a contributor that has lots of examples.
https://github.com/ustaxcourt/ef-cms/tree/staging/web-client/pa11y

**Comment by josebolos** [comment]
Closing old issue as the user doesn't exist any more.
