### ISSUE TITLE
Sharing a pa11y-ci + GitHub actions article

### ISSUE THREAD

**Issue by dmundra** [pa11y/pa11y-ci#130]
Hi,

I wanted to share that we have pa11y-ci working with GitHub actions and we wrote this article https://accessibility.civicactions.com/posts/automated-accessibility-testing-leveraging-github-actions-and-pa11y-ci-with-axe

Let me know if it could be added to the readme and I can submit a PR.

Thanks,
Daniel

**Comment by josebolos** [comment]
Hi @dmundra 

Apologies for the late reply. The article looks great! We have a page on our site with tutorials, so I've just added it there:
https://pa11y.org/tutorials/

Thanks for the article!
