### ISSUE TITLE
Additional copies of puppeteer get installed when using pa11y-ci

### ISSUE THREAD

**Issue by redgardner** [pa11y/pa11y-ci#131]
With the latest version of pa11y (5.3.1) there was a change from puppeteer ^1.13.0 to ~1.19.0

Pa11y-ci 2.4.0 consumes the latest version of pa11y and also requires puppeteer ~1.20.0. This means that 1.19 and 1.20 both get installed when using pa11y-ci

This means that any repo that uses pa11y-ci will get a double install of puppeteer from using different versions. As pa11y-ci requires pa11y and therefore puppeteer and pa11y-ci requires puppeteer what can be done to bring these into alignment so that there aren't 2 installs of chromium for anyone using pa11y-ci and reduce package bloat?

**Comment by josebolos** [comment]
Hi @redgardner,

Thanks for creating the issue. You're right, we can't remove the puppeteer dependency from pa11y-ci, but it should be pinned to use the same version as pa11y does so it doesn't download twice.

Unfortunately development of pa11y-ci is stopped at the moment so we can't make this change right now, but please keep an eye on this issue and I'll update it as soon as it's fixed.

Thanks again.

**Comment by josebolos** [comment]
This has now been fixed in [version 2.4.1](https://github.com/pa11y/pa11y-ci/blob/master/CHANGELOG.md#241-2021-04-25).

Thanks again for creating the issue, @redgardner!

**Comment by redgardner** [comment]
@josebolos  Thanks so much! I'm not seeing a tag for 2.4.1, am I missing something? 

Just wanted to check so I can ensure we're consuming this fix

**Comment by josebolos** [comment]
@redgardner Ah, you're right, I forgot to push the right button. 2.4.1 is now tagged and available on npm: https://www.npmjs.com/package/pa11y-ci
