### ISSUE TITLE
pa11y-ci using puppeteer@1.19.0 which has dependency ws@6.2.1 with npm vulnerability 1748

### ISSUE THREAD

**Issue by ap-buf** [pa11y/pa11y-ci#141]
├─┬ pa11y-ci@2.4.1
│ ├─┬ pa11y@5.3.1
│ │ └─┬ puppeteer@1.19.0
│ │   └── ws@6.2.1  deduped
│ └─┬ puppeteer@1.19.0
│   └── ws@6.2.1  deduped

https://www.npmjs.com/advisories/1748

The latest version of puppeteer (10.0.0) is using ws@7.4.6 and does not have this vulnerability. 

Would it be possible to include an updated version of puppeteer in your next release. Note also the dependency through pa11y.

**Comment by masi** [comment]
I'm using BackstopJS which has already upgraded to 10. Thanks to requiring puppeteer again I have now 3 local Chromiums. :(

Cannot pa11y-ci reuse the Chromium that came with pa11y?

**Comment by josebolos** [comment]
Hi @masi

Your issue seems to be unrelated to this one. Could you please create a new issue and fill up all the details about what version and environment are you using? Thanks.

**Comment by masi** [comment]
Sorry. Besides the issue of ap-buf about the vulnerability which is also a concern for me I should not have added another problem.

**Comment by josebolos** [comment]
Version 3 of `pa11y-ci` is using version 9 of puppeteer, so I'm closing this issue.
