### ISSUE TITLE
Does not pickup Table Has No TH

### ISSUE THREAD

**Issue by smustgrave** [pa11y/pa11y-ci#142]
Tables should have to have a header or role presentation but currently only check seems to be manually.  Could pa11y be configured to pick these up?

**Comment by josebolos** [comment]
Hi @smustgrave,

Thanks for creating this issue. You're right in that tables need either headers in the case of a data table, or `role="presentation"` in the case of layout tables.

Unfortunately, Pa11y is not able to mark these as an issue. Pa11y is only able to use the tests as provided by HTML_CodeSniffer (the default), or axe, so it's up to them to implement this guidance. Neither of them currently have tests for this issue as far as I know.
