### ISSUE TITLE
Ignore rule while using Axe runner

### ISSUE THREAD

**Issue by smustgrave** [pa11y/pa11y-ci#145]
https://github.com/dequelabs/axe-core/issues/3034 opened this up with Axe.  But wondering if there's a way to ignore a rule while using axe? 
{
  "defaults": {
    "standard": "WCAG2AA",
    "runners": ["axe"],
    "timeout": 90000,
    "level": "none",
    "chromeLaunchConfig": {
      "ignoreHTTPSErrors": true,
      "args": ["--no-sandbox"]
    },
    "ignore": [
      "Section508.D.H49.AlignAttr",
      "Section508.D.HeadingOrder",
      "WCAG2A.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1_AAA.G141"
    ]
  }
}

this is my config file but axe skips the ignore.

**Comment by joeyciechanowicz** [comment]
Currently the `ignore` section is only used by `HTML_CodeSniffer`, this support needs to be added to the axe runner.

**Comment by smustgrave** [comment]
Thanks a lot! Saw the merge does this mean axe will ignore now? Same syntax?

**Comment by joeyciechanowicz** [comment]
Same syntax, though it will only work if you get latest from Github. This will be released with pa11y v6

**Comment by smustgrave** [comment]
So I'm trying this
{
  "defaults": {
    "standard": "WCAG2AA",
    "runners": ["axe"],
    "timeout": 90000,
    "level": "none",
    "chromeLaunchConfig": {
      "ignoreHTTPSErrors": true,
      "args": ["--no-sandbox"]
    },
    "ignore": [
      "Section508.D.H49.AlignAttr",
      "Section508.D.HeadingOrder",
      "WCAG2A.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AA.Principle1.Guideline1_3.1_3_1.G141",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
      "WCAG2AAA.Principle1.Guideline1_3.1_3_1_AAA.G141"
    ]
  }
}

And it's not ignoring.
