### ISSUE TITLE
Consider improving log output for Travis (and other CI systems)

### ISSUE THREAD

**Issue by andrewmee** [pa11y/pa11y-ci#15]
It might be nice to include some way of organising the log output in people's chosen CI systems.

For example in Travis, it's possible to [include collapsed sections](http://enricostano.github.io/articles/dealing-with-travis-ci-console-output/) to help make the logs more readable.

This could be useful for helping to organise the output when pa11y is being run on very large sitemaps for example.

**Comment by greggles** [comment]
The new `--reporter ` argument should make it possible to build CI-focused writers.

**Comment by josebolos** [comment]
Given that a lot of people (including this project) has migrated away from Travis, I'm going to close this issue. We'll be more than happy to add any similar features if anyone fancies creating a PR.
