### ISSUE TITLE
Ignore Rules when using Axe

### ISSUE THREAD

**Issue by smustgrave** [pa11y/pa11y-ci#156]
So I'm trying this
{
"defaults": {
"standard": "WCAG2AA",
"runners": ["axe"],
"timeout": 90000,
"level": "none",
"chromeLaunchConfig": {
"ignoreHTTPSErrors": true,
"args": ["--no-sandbox"]
},
"ignore": [
"Section508.D.H49.AlignAttr",
"Section508.D.HeadingOrder",
"WCAG2A.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
"WCAG2AA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
"WCAG2AA.Principle1.Guideline1_3.1_3_1.G141",
"WCAG2AAA.Principle1.Guideline1_3.1_3_1.H49.AlignAttr",
"WCAG2AAA.Principle1.Guideline1_3.1_3_1_AAA.G141"
]
}
}

And it's not ignoring. Tested with htmlcs and works fine.
Updated pa11y to 6.0.1 beforehand.
I'm also using latest pa11y-ci

**Comment by smustgrave** [comment]
Related to 
https://github.com/pa11y/pa11y/pull/592
https://github.com/pa11y/pa11y-ci/issues/145

**Comment by joeyciechanowicz** [comment]
Those are htmlcs rules, axe has different names for rules. 
https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md
