### ISSUE TITLE
No `--reporter` cli flag available

### ISSUE THREAD

**Issue by jasikpark** [pa11y/pa11y-ci#157]
Either the docs are incorrect or the tool is incorrect - the docs say there's a flag to `--reporter` to specify where to send the logs and I gave it this:

```shell
yarn workspace docs pa11y-ci --sitemap 'https://astro-docs-git-docs-improve-a11y-pikapkg.vercel.app/sitemap.xml' --sitemap-find 'https://docs.astro.build' --sitemap-replace 'https://astro-docs-git-docs-improve-a11y-pikapkg.vercel.app' --reporter ~/Downloads/astro-docs-improve-a11y.log
```

With this output: `error: unknown option `--reporter'`

**Comment by sangitamane** [comment]
Hi @jasikpark, thanks for using Pa11y!

We need to give option for reporter to chose from, adding `cli` for the included default CLI reporter next to --reporter should work!

Hope this helps!

**Comment by jasikpark** [comment]
Ah, in that case could the description be updated to the fact that the `local file` must be a JS script that can consume the output? I wanted to have the output piped into a file...

**Comment by jasikpark** [comment]
Thanks for the great tool anyways!
