### ISSUE TITLE
reporters  unknown option `--html`, `--reporter` & not working defaults.reporters in config.json

### ISSUE THREAD

**Issue by AdamDomagalsky** [pa11y/pa11y-ci#160]
pa11y-ci:2.4.2

According to [reporters](https://github.com/pa11y/pa11y-ci#reporters) documentation, there shall be option for html reporter by defining via 2 options:
> None of the below are working
1. Within config.json>defaults>reporters
2. Via CLI option `--reporter=pa11y-reporter-html`

- ✅ `pa11y-ci --config config.json --sitemap http://web:3000/sitemap.xml`
- ❌ `pa11y-ci --config config.json --sitemap http://web:3000/sitemap.xml --html`
- ❌ `pa11y-ci --config config.json --sitemap http://web:3000/sitemap.xml --reporter=pa11y-reporter-html`

![2021-09-15 at 2 27 PM](https://user-images.githubusercontent.com/22766479/133433357-bef3411f-7671-4473-b917-90d7f374c6ba.png)

config.json:
```json
{
    "defaults": {
        "reporters": [
            "cli",
            "pa11y-reporter-html",
            "json"
        ],
        "chromeLaunchConfig": {
            "args": [
                "--no-sandbox"
            ]
        }
    }
}

**Comment by masi** [comment]
You are looking at the documentation of the master branch. Switch to tag 2.4.2 in the Github UI and you see that there is no support for reporters in the last stable release.

I don't know what is holding back the next release. I am waiting for the reporters to use pa11ly-ci in my CI.
