### ISSUE TITLE
Option to pass environment variable in .pa11yci file

### ISSUE THREAD

**Issue by mudit94** [pa11y/pa11y-ci#193]
Hi Team,
I am looking for a way to be able to use environment variables in pa11yci file so that credentials need not be hardcoded

**Comment by aarongoldenthal** [comment]
Hi @mudit94,

Pa11y CI will actually accept either a JSON or JavaScript formatted configuration file (although looking at the docs that's not 100% clear). By default (i.e. if the `--config` CLI argument is not specified), it will try `.pa11yci`, then `.pa11yci.js`, then `.pa11yci.json` (per the code [here](https://github.com/pa11y/pa11y-ci/blob/master/bin/pa11y-ci.js#L124-L130) if that's helpful).

So, the easiest route is to declare variables with your credentials, then use a JavaScript formatted config file to pull them, something like (assuming the `AUTH_TOKEN` environment variable has an auth token):

`.pa11yci.js`:

```js
module.exports = {
{
  defaults: {
    headers: {
      'auth-token': process.env.AUTH_TOKEN
    }
  },
  urls: [...]
}
```

There are other tricks for variable substitution (e.g. something like `sed` in Linux), but that's nearly as clean.

**Comment by mudit94** [comment]
I want to use the variable in actions to be able to perform login operation. Do you have a sample code?

**Comment by aarongoldenthal** [comment]
@mudit94 How specifically are you trying to login? Is it with some kind of access token in the `headers` as shown above, using `actions` to fill out form fields, or something else?

**Comment by danyalaytekin** [comment]
Thanks for your help here @aarongoldenthal.  I've also added #197 to the list for [release 3.1](https://github.com/pa11y/pa11y-ci/milestone/3).  @mudit94, I'll close this now as it's been a while, but please reopen if you'd like to continue the conversation.
