### ISSUE TITLE
Use the update-notifier package

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y-ci#21]
I think we should try using the [update-notifier package](https://www.npmjs.com/package/update-notifier) to let people know when the command-line interface is out of date. It's used by thousands of other packages and should help us keep users up to date. See also https://github.com/pa11y/pa11y/issues/254

**Comment by josebolos** [comment]
Given that most of our users seem to use the tool in CI environments, where a new version of the tool will be installed for every single run, I feel we shouldn't probably add this. Adding it may also create additional networks requests and potential timeouts on testing and CI environments that may sometimes be fairly restricted in terms of network/CPU usage, and we may inadvertently add another single point of failure.
