### ISSUE TITLE
pa11y-ci not producing json output

### ISSUE THREAD

**Issue by berthelemy** [pa11y/pa11y-ci#24]
When I run the command:

pa11y-ci --json -s "http://example.com/sitemap.xml" > temp/pa11y-ci-report.txt

All I get is a blank file.

When I run it as:
pa11y-ci -s "http://example.com/sitemap.xml" > temp/pa11y-ci-report.txt

I just get a file with the first line of the output:

> Running Pa11y on 62 URLs:

Nothing else is output.

How can I get pa11y-ci to send the whole report to a file, ideally as JSON or CSV?

Thanks,

Mark

**Comment by rowanmanning** [comment]
Hi @berthelemy, I'm unable to replicate this, and the following works fine for me. Could you try this and let me know whether you get JSON in the `example.txt` file?

```
pa11y-ci --json --sitemap http://pa11y.org/sitemap.xml > example.txt
```

If it doesn't work, then could you let me know your Node.js and Pa11y CI versions, and maybe send me a copy of the sitemap you're using?

**Comment by surendraJ** [comment]
I don't have any issues with pa11y-ci --json --sitemap http://pa11y.org/sitemap.xml > example.txt . 

@rowanmanning I am wondering is there any way to generate html page output using multiple urls? Lets take one scenario,  
I have multiple url in pa11yci.sjon file and I want to save reports to html file so that I can easily embed to Jenkins for report. Is there any way to do?

**Comment by bharath4793** [comment]
is there any way to generate html page output using multiple urls?

I have multiple url in pa11yci.sjon file and I want to save reports to html file so that I can easily embed to Jenkins for report. Is there any way to do?

**Comment by rowanmanning** [comment]
No, there's currently no way out outputting HTML reports for multiple URLs. We could investigate adding this in future if enough people need it but it feels more like something that [Sidekick](https://github.com/pa11y/sidekick) would cater for.

Either way it's not relevant to this issue, which is about the JSON reporter. Could you open another one requesting the feature, or decide if Sidekick would work for you?

**Comment by rgjain** [comment]
Just discovered this [pa11y-ci-reporter-html](https://www.npmjs.com/package/pa11y-ci-reporter-html) which can generate HTML report out of the JSON report.

Refer the documentation for the usage.

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this may be fixed now, feel free to reopen the issue if not.
