### ISSUE TITLE
Support for pa11y 5.0.0 (beta)

### ISSUE THREAD

**Issue by kaelig** [pa11y/pa11y-ci#28]
Thank you for the great ci tool. I'd love to see it support the very new pa11y 5.0.0-beta!

**Comment by rowanmanning** [comment]
Absolutely, we'll be doing this ASAP. Because we'll be dropping Node.js <8 support at the same time I'd also like to refactor to use `async`/`await`

**Comment by andrewmee** [comment]
I've started this work in a new pa11y-ci 2.x branch, you can see progress in the open PR https://github.com/pa11y/pa11y-ci/pull/34

**Comment by jtreas** [comment]
Hi, we are looking forward to this release as we need the Headless Chrome capability.  Is there any news on a release approval date?

**Comment by rowanmanning** [comment]
Hi @jtreas, yes we should be merging and releasing quite soon. #34 is pretty much ready to go, we just need to coordinate the release :)

**Comment by andrewmee** [comment]
Pa11y-ci 2.0.0 (using Pa11y 5.x) is now complete and available from npm :) Enjoy @kaelig @jtreas
