### ISSUE TITLE
Get "Failed to run" on urls and Truffler timeout

### ISSUE THREAD

**Issue by stevenadams** [pa11y/pa11y-ci#31]
Running node 8.4
I keep getting  `> http://pa11y.org/contributing - Failed to run` and ` • Error: Truffler timed out (1000ms)` using the demo .pallyci file from the readme

**Comment by emmasax** [comment]
Just leaving a comment here in case it helps anyone: I was getting this exact issue and I increased the timeout in the config from 1000 to 10000

```
{
	"defaults": {
		"timeout": 10000
        }
}
```

**Comment by rgjain** [comment]
Thanks @emmasax This works. Looks like 1000ms was not sufficient for the page to load.

**Comment by rowanmanning** [comment]
Thanks for the response @emmasax :) we've been working hard on Pa11y 5.x which should make it into Pa11y CI soon. Then any Truffler/PhantomJS issues should go away 🤞
