### ISSUE TITLE
Support path globbing for scanning local html files

### ISSUE THREAD

**Issue by phillbaker** [pa11y/pa11y-ci#37]
Hello and thanks for all of the hard work on this!

Would folks be interested in a PR to add a path globbing argument to the CLI? While evaluating different accessibility scanners I came across [an example (last one in the section)](https://github.com/addyosmani/a11y#example) that proved to be very helpful for our CI setup for static sites.

Happy to provide more context as well.

**Comment by rowanmanning** [comment]
Yes I'd be open to a PR adding this for local files 👍
