### ISSUE TITLE
When I use pally-ci with localhost I get NO errors, but external urls I get correct errors 

### ISSUE THREAD

**Issue by jasperswart** [pa11y/pa11y-ci#41]
When I use pally-ci with localhost I get NO errors, but external urls I get correct errors and warnings.

Does anyone have this issue also.

my .pa11yci.js
```
module.exports = {
    urls: [
        'http://localhost:8080/#?mpb=topografie&mpz=11&mpv=52.3731081:4.8932945&pgn=home',
        'http://localhost:8080/#?dsd=bag&dsp=1&dsv=TABLE&mpb=topografie&mpz=11&mpv=52.3731081:4.8932945'
    ]
}
```

external:
```
module.exports = {
    urls: [
        'http://data.amsterdam.nl/#?mpb=topografie&mpz=11&mpv=52.3731081:4.8932945&pgn=home',
        'http://data.amsterdam.nl/#?dsd=bag&dsp=1&dsv=TABLE&mpb=topografie&mpz=11&mpv=52.3731081:4.8932945'
    ]
}
```

**Comment by rowanmanning** [comment]
Hi @jasperswart, I've not come across this before, seems odd. Is there anything different that your application does in production vs local? Difficult to verify without running locally myself, but a few things that _could_ affect this:

  - Advertising
  - Tracking scripts
  - Different information displayed because production database has more in it

**Comment by jasperswart** [comment]
thanks...

i am looking this now and i think it is not connected to pa11y-ci. 

i will keep you updated when i find the problem!

**Comment by jasperswart** [comment]
i found the problem: pa11y itself is returning no errors, but when I use pa11y v5 it does!

do you have any idea when will you be going to implement pa11y 5?

**Comment by rowanmanning** [comment]
Ah, I didn't think there were any differences in the errors between those two. Do you have the exact two versions of Pa11y that you're using?

Pa11y 5 will hopefully be released by the end of this year. If not then early January. Most of the core team has ended up being quite busy with work in the lead up to Christmas :)

**Comment by andrewmee** [comment]
Hi @jasperswart,

I don't suppose this issue is still relevant.  Is the new release of Pa11y working for you?

I'm wondering if I can close this issue.

**Comment by ecerta** [comment]
Hi there. I'm running into this issue with pa11y v5 as well. To add another wrinkle, http://localhost:4200 (homepage) works great but if anything else is tacked on, whether it's a querystring or new path, I get no errors reported locally and correct errors reported on the link proper. We have no ads and the only tracking software we use is google analytics, which I doubt would impact the site like this.

**Comment by rowanmanning** [comment]
Hi @ecerta, I can investigate. Would it be possible to open a new issue with a few more details? Mostly useful to know if the application is all client-side or React etc, or if the different pages are served by a back-end.

Going to close this issue now, can reopen if @jasperswart is still seeing the original behaviour.
