### ISSUE TITLE
Is there a way to generate html report using pa11y-ci

### ISSUE THREAD

**Issue by bharath4793** [pa11y/pa11y-ci#42]
is there any way to generate html page output using multiple urls?

I have multiple url in pa11yci.sjon file and I want to save reports to html file so that I can easily embed to Jenkins for report. Is there any way to do?

**Comment by rowanmanning** [comment]
No, there's currently no way out outputting HTML reports for multiple URLs. We could investigate adding this in future if enough people need it but it feels more like something that [Sidekick](https://github.com/pa11y/sidekick) would cater for.

Let me know if that is likely to suit your needs. I'm going to close this for now as we're not intending on adding any time soon, but we can reopen if we decide to.

**Comment by sshaar08** [comment]
+1

**Comment by lsigism** [comment]
I know that the ticket is closed but yesterday I was thinking the same (in a way to generate html report using pa11y-ci) and unfortunately we have our negative answer. Maybe for the future, we could even consider this report and also an aggregate results view. For example, showing how many times a specific rule failed across all the URLs tested, something like that (ordering by the rule with more failed results, or for the 'most' important to the 'less' important one). 
But thanks for getting back to us Rowan 👍

**Comment by dgateles** [comment]
+1

**Comment by aarongoldenthal** [comment]
For my use case I'm frequently looking for CI jobs that produce a couple of outputs - something machine readable like JSON that can be ingested for a summary of all analyses/tests for a project, and something easily human-readable like HTML.

To meet that need I built a simple [Pa11y CI HTML Reporter](https://www.npmjs.com/package/pa11y-ci-reporter-html).  Unlike pa11y reporters it runs standalone, but takes a `pa11y-ci` JSON file, uses the existing `pa11y-reporter-html` module to generate HTML reports for each URL, and also generates a summary page (similar format to the individual URL reports, just showing error/warning/notice counts and linking to the detailed page reports).

**Comment by XhmikosR** [comment]
@aarongoldenthal that looks pretty good! Would be nice if your package was listed somewhere in docs or got more visibility someway.
