### ISSUE TITLE
Request for feedback - badges, '--init' flag, environment variables [enhancement ideas]

### ISSUE THREAD

**Issue by nfreear** [pa11y/pa11y-ci#48]
Hi,

I'm loving and using `pa11y-ci`. Thank you to all contributors, and the pa11y team!

I've got some suggestions and ideas, that I'd like some feedback on.

Then I may be able to implement them, and create a pull request ...

 1. Suggest badges (via https://shields.io) in the documentation for use in READMEs to promote pa11y-ci, for example, [![Accessibility testing][pa11y-icon]][pa11y-ci]
    ```
    [![Accessibility testing](https://img.shields.io/badge/accessibility-pa11y--ci-blue.svg)](https://github.com/pa11y/pa11y-ci)
    ```

 2. An `--init` or `--defaults` flag.
    `pa11y-ci --init` would interactively create a `.pa11yci.json` file, rather like `npm init`
    `pa11y-ci --defaults > .pa11yci.json` would dump a default configuration to file.
    (Example, https://gist.github.com/nfreear/785dce9698bcd9656b6d3fa5ffee9b47)

 3. Support for environment variables in `.pa11yci.json` files.
    Why? Useful when running tests on multiple URLs on a visible, but un-advertised test-server,

    Example,
    ```sh
    export TEST_SRV=https://test.example.org  # Or, set via Travis-CI user-interface.

    pa11y-ci -C .pa11yci.json
    ```
    Then,
    ```json
    {
      "defaults": { },
      "urls": [
        "${TEST_SRV}/page1.html",
        "${TEST_SRV}/page2.html",
        "${TEST_SRV}/page3.html",
      ]
    }
    ```

Yours,

Nick

_(FYI, I've recently [blogged about my use of `pa11y-ci`][blog].)_

[blog]: https://nick.freear.org.uk/2018/03/02/pa11y-ci-accessility-testing.html
[pa11y-ci]: https://github.com/pa11y/pa11y-ci
    "Automated accessibility testing - via 'pa11y-ci'"
[pa11y-icon]: https://img.shields.io/badge/accessibility-pa11y--ci-blue.svg
[wcag-icon]: https://img.shields.io/badge/accessibility-WCAG_2.0_AAA-green.svg

---

**Comment by nfreear** [comment]
Hi,

To follow-up, I've answered one of my enhancement ideas ...

Point 3, _Support for environment variables_ -- `pa11y-ci` accepts configuration files as JSON or Javascript -- in either case they are `required` by pa11y-ci. So, the following works.

[`.pa11yci.conf.js` on Gist][gist]:
```js
/*!
  Pa11y-ci Configuration.
  Dynamically generate a '.pa11yci' JSON config object, using an environment variable.
*/

var defaults = {
  standard: 'WCAG2AA',
  timeout: 5000
  // More ...
};

var urls = [
  '${TEST_SRV}/page1.html?_ua=pa11y',
  '${TEST_SRV}/page2.html?_ua=pa11y'
];

function myPa11yCiConfiguration () {

  console.error('Env:', process.env.TEST_SRV);

  for (var idx = 0; idx < urls.length; idx++) {
    urls[ idx ] = urls[ idx ].replace('${TEST_SRV}', process.env.TEST_SRV);
  }

  return {
    defaults: defaults,
    urls: urls
  }
};

// Important ~ call the function, don't return a reference to it!
module.exports = myPa11yCiConfiguration();
```

Then call with:

```sh
export TEST_SRV=https://test.example.org  # Or, set via Travis-CI user-interface.

pa11y-ci -c .pa11yci.conf.js
```

Yours,

Nick

[gist]: https://gist.github.com/nfreear/cece86bf6d5d4d531bf0646417a868fb ".pa11yci.conf.js"

**Comment by josebolos** [comment]
Closing as per @rowanmanning's comment above.
