### ISSUE TITLE
Error running pa11y-ci against a url with basic authentication. 

### ISSUE THREAD

**Issue by dkay703** [pa11y/pa11y-ci#57]
Hi, I am working to run pa11y-ci using a custom config file with credential. I referred to "How can Pa11y log in if my site's behind basic auth?" from pa11y github but an error "pa11y is not defined" returns.

**config.js script:**
const credentials = 'mycredential:mypassword';
const encodedCredentials = new Buffer(credentials).toString('base64');

pa11y('https://my.example.com', {
    headers: {
        Authorization: `Basic ${encodedCredentials}`
    }
});
 
**pa11y-ci -c config.js output:**
There was a problem loading "/opt/pa11y-ci/pa11y-ci-master/config":
ReferenceError: pa11y is not defined
    at Object.<anonymous> (/opt/pa11y-ci/pa11y-ci-master/config.js:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLocalConfigWithJs (/usr/lib/node_modules/pa11y-ci/bin/pa11y-ci.js:166:10)
    at Promise (/usr/lib/node_modules/pa11y-ci/bin/pa11y-ci.js:120:14)

Please let me know if you need more information.
Thank you in advance !

**Comment by rowanmanning** [comment]
Ah yes the issue is with your config. The config should be an exported object rather than JS code which runs with Pa11y. The following may work for you:

```js
const credentials = 'mycredential:mypassword';
const encodedCredentials = new Buffer(credentials).toString('base64');

module.export = {
    defaults: {
        headers: {
            Authorization: `Basic ${encodedCredentials}`
        }
    },
    urls: [
        'https://my.example.com'
    ]
};
```

**Comment by dkay703** [comment]
@rowanmanning 
Thank you for replying. Unfortunately, i'm getting the same 401 error.

Couple ways I configured config.js file is 
**1. The way you suggested, replacing "mycredential", "mypassword", and "urLs" accordingly.**

const credentials = 'mycredential:mypassword';
const encodedCredentials = new Buffer(credentials).toString('base64');

module.export = {
    defaults: {
        headers: {
            Authorization: `Basic ${encodedCredentials}`
        }
    },
    urls: [
        'https://my.example.com'
    ]
};

**2. I also tried base 64ing the credential and commenting out two const at the top**

//const credentials = '1000000003:dev1234$$';
//const encodedCredentials = new Buffer(credentials).toString('base64');

module.export = {
    defaults: {
        headers: {
            Authorization: 'Basic hashed_credential'
        }
    },
    urls: [
        'https://myurl'
    ]
};

Both returns 401. In addition, I have noticed if i just run **$pa11y-ci -c config.js**, it doesn't pick up the url specified in the config. I have to specify the url in command line for pa11y to test against it for some reason i.e. **$pa11y-ci -c config.js https://myurl.com**

Thank you for the assistance !

**Comment by seanahern** [comment]
Typo in the sample answer at s/`module.export`/`module.exports` but this helped!

Create some file, like `pa11y-config.js`:
```
const credentials = 'mycredential:mypassword';
const encodedCredentials = new Buffer(credentials).toString('base64');

module.exports = {
    defaults: {
        headers: {
            Authorization: `Basic ${encodedCredentials}`
        }
    },
    urls: [
        'https://my.example.com'
    ]
};
```
Run

`pa11y-ci --config=./pa11y-config.js`
