### ISSUE TITLE
Pa11y-CI and --sitemap only shows errors and no warnings

### ISSUE THREAD

**Issue by bgarrant** [pa11y/pa11y-ci#71]
I have been trying to get Pa11y-CI to show warnings to me as well while using the `--sitemap` feature.  It will only show errors for some reason.

`pa11y-ci --sitemap http://domainname/sitemap --include-warnings` fails with `error: unknown option `--include-warnings'`

`pa11y-ci http://domainname --include-warnings` works as expected

How can I get warnings to also show when using the `--sitemap` option?

**Comment by bgarrant** [comment]
I tried every config I can think of and I can't get warnings to show when using the `----sitemap` option.  Can we get this function added if it does not exist?

**Comment by bgarrant** [comment]
These would be great if they could be added. 
```
--include-notices              Include notices in the report
--include-warnings             Include warnings in the report
```

**Comment by tomukasas** [comment]
`pa11y-ci` is using `pa11y` as a dependency, so you can pass `includeWarnings` option and the warnings will be displayed. Example config file (I am using `js`):

`
module.exports = {
  "defaults": {
    "timeout": 30000,
    "viewport": {
      "width": 320,
      "height": 480
    },
    "chromeLaunchConfig": {
      "ignoreHTTPSErrors": true
    },
    "includeWarnings": true // <-- this line
  }
}
`

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this is now fixed, feel free to reopen the issue if not.
