### ISSUE TITLE
Run into "Protocol error (Target.createTarget): Target closed" with node 8.11.2

### ISSUE THREAD

**Issue by epifab** [pa11y/pa11y-ci#75]
We're running a set of three tests in our project.
The first one seems to run just fine, however, all the other tests fail to run:
```
Running Pa11y on 3 URLs:
 > https://video-qa.springernature.app/video - 0 errors
 > https://video-qa.springernature.app/video/segment/10.1007/978-1-4842-3635-2_2 - Failed to run
 > https://video-qa.springernature.app/video/10.1007/978-1-4842-3635-2 - Failed to run

Errors in https://video-qa.springernature.app/video/segment/10.1007/978-1-4842-3635-2_2:
 • Error: Protocol error (Target.createTarget): Target closed.

Errors in https://video-qa.springernature.app/video/10.1007/978-1-4842-3635-2:
 • Error: Navigation failed because browser has disconnected!
```

I found out (by chance) that downgrading node to 8.0.0 makes the error go away.
This currently happens with pa11y-ci 1.2.1
Happy to provide more details if required. Thank you!

**Comment by epifab** [comment]
Did some more testing, it looks like the alleged bug was introduced with version of node 8.7.0

**Comment by josebolos** [comment]
Thanks for creating the issue! This is now fixed after several puppeteer and HTML_CodeSniffer upgrades.
