### ISSUE TITLE
Pa11y-CI cannot be run on https with self-signed certificate

### ISSUE THREAD

**Issue by AssassinLV** [pa11y/pa11y-ci#80]
When running Pa11y-CI on test environment with self-signed certificate - then the exception:
 "Error: net::ERR_CERT_AUTHORITY_INVALID at https://_ _ _" is thrown. Had tried to use "ignoreHTTPSErrors" but it had no effect.

Is there no way currently to "ignore" the cert errors? Also I think that ignoring cert errors should be default behavior.

**Comment by aarongoldenthal** [comment]
Did you set `ignoreHTTPSErrors` as part of the `chromeLaunchConfig`?  This works for me:

```
{
    "defaults": {
        "chromeLaunchConfig": {
            "ignoreHTTPSErrors": true
        }
    }
}
```

**Comment by AssassinLV** [comment]
I've tried - but in the ends I just made a new self signed certificate and added it on "Trusted Root Authorities" :)

**Comment by drnickyoung** [comment]
Was this ever resolved, using the config scripts that is? I am facing the same error using:

```
{
    "default": {
        "chromeLaunchConfig": {
            "ignoreHTTPSErrors": true
        },
        "standard": "WCAG2AA",
        "timeout": 5000,
        "wait": 2000,
        "page": {
            "viewport": {
                "width": 320,
                "height": 480
            }
        }
    },
    "urls": [
        "https://xyz/",
        "https://xyz/about"
    ]
}
```

and getting this back:

```
Errors in https://xyz/:

 • Error: net::ERR_CERT_AUTHORITY_INVALID at https://xyz/
```

I have used ignoreHTTPSErrors in pa11y-dashboard config and it works fine at ignoring the certificate issue. Just Pa11y-ci doesn't seem to use it in the config, ot I am doing something wrong.

**Comment by aarongoldenthal** [comment]
@drnickyoung If that's a copy from your configuration, check the spelling of the `"defaults"` property.

**Comment by drnickyoung** [comment]
@aarongoldenthal Oops, lack of sleep! Unfortunately even with that corrected still getting errors, failing to run. Anyway different errors (not HTTPS/ CERTIFICATE), so will try bit of debugging and raise another issue with appropriate errors. Thanks.

**Comment by josebolos** [comment]
Thanks for creating this issue. It looks like this is now fixed, feel free to reopen the issue if not.
