### ISSUE TITLE
Problems with absolute paths to configuration file

### ISSUE THREAD

**Issue by AssassinLV** [pa11y/pa11y-ci#82]
I can't give an absolute path to the config file....
Here is a result that I would get:
![image](https://user-images.githubusercontent.com/30855600/58780715-75fb0900-85e2-11e9-9e37-a95ba7f1e98b.png)

It should first check whether the path is not an absolute path before appending to the current directory.

**Comment by greggles** [comment]
#122 looks like it would fix this issue which appears to only affect windows.

**Comment by josebolos** [comment]
This is now fixed in v3.0.0.
