### ISSUE TITLE
Running against sitemap index doesn't validate any URLS

### ISSUE THREAD

**Issue by sddaniels** [pa11y/pa11y-ci#84]
Many sites have large sitemaps that are broken up into individual files and coordinated by a sitemap index file. A common example of this is the functionality of the Yoast SEO plugin for WordPress.

More information here about how this works:
https://support.google.com/webmasters/answer/75712?hl=en

When Pa11y CI runs against an index file, it does not find any pages to run against and exits. This means that in order to scan an entire site, you need to run the tool against each individual sitemap listed in the index file.

The desired behavior would be to work recursively and conduct a full site scan when given an index file.

**Comment by einSelbst** [comment]
+1 Ghost bloging platform would be another example with such sitemaps

https://ghost.org/sitemap.xml
https://ghost.org/blog/advanced-sitemaps-gatsby/
